defaultBaseImage: gcr.io/distroless/base-debian12:nonroot
builds:
- id: headscale
  main: ./cmd/headscale
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X github.com/juanfont/headscale/hscontrol/types.Version={{.Env.VERSION}}
  - -X github.com/juanfont/headscale/hscontrol/types.GitCommitHash={{.Env.COMMIT}}